# Generated by Django 4.2 on 2023-04-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
        ("borrow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrow",
            name="book",
        ),
        migrations.AddField(
            model_name="borrow",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrows",
                to="book.book",
            ),
            preserve_default=False,
        ),
    ]
