# Generated by Django 4.2 on 2023-04-24 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "cover",
                    models.CharField(
                        choices=[("Hardcover", "Hard"), ("Softcover", "Soft")],
                        max_length=255,
                    ),
                ),
                (
                    "inventory",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("daily_fee", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "unique_together": {("title", "author")},
            },
        ),
    ]
