# Generated by Django 4.2 on 2023-04-25 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
